# Generated by Django 3.1.3 on 2022-04-30 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_remove_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='recipes'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
