# Generated by Django 3.1.3 on 2022-04-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_auto_20220420_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(upload_to='recipes'),
        ),
    ]
